/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package concesionarioapp;

import java.awt.Toolkit;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

/**
 *
 * @author User
 */
public class Agendar_cita_cliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Agendar_cita_cliente.class.getName());

    /**
     * Creates new form Agendar_cita_cliente
     */
    public Agendar_cita_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        btnAgendar = new javax.swing.JButton();
        lblMotivo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        cboMotivo = new javax.swing.JComboBox<>();
        cboPeriodo = new javax.swing.JComboBox<>();
        btnLimpiar = new javax.swing.JButton();
        lbllogo = new javax.swing.JLabel();
        btnRetroceder = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Nombre completo");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 140, -1));

        lblID.setForeground(new java.awt.Color(0, 0, 0));
        lblID.setText("Numero de identificación");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha.setText("Fecha");
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 64, -1));

        lblHora.setForeground(new java.awt.Color(0, 0, 0));
        lblHora.setText("Hora");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 37, -1));

        btnAgendar.setBackground(new java.awt.Color(153, 255, 153));
        btnAgendar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/citas.png"))); // NOI18N
        btnAgendar.setText("Agendar cita");
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        lblMotivo.setForeground(new java.awt.Color(0, 0, 0));
        lblMotivo.setText("Motivo de cita");
        getContentPane().add(lblMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 122, -1));

        txtNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 120, -1));

        txtID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDKeyPressed(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 120, -1));

        txtFecha.setText("DD/MM/AAAA");
        txtFecha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        txtHora.setText("HH:MM");
        txtHora.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 71, 30));

        cboMotivo.setBackground(new java.awt.Color(51, 153, 255));
        cboMotivo.setForeground(new java.awt.Color(0, 0, 0));
        cboMotivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ver vehículo en venta", "Cotizar vehículo usado", "Prueba de manejo", "Negociar precio o financiación", "Documentación", "Otro" }));
        cboMotivo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(cboMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        cboPeriodo.setBackground(new java.awt.Color(51, 153, 255));
        cboPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        cboPeriodo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(cboPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 80, 30));

        btnLimpiar.setBackground(new java.awt.Color(255, 51, 51));
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/limpiar.png"))); // NOI18N
        btnLimpiar.setText("limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 110, -1));

        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/fondo1.png"))); // NOI18N
        getContentPane().add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 110, 50));

        btnRetroceder.setBackground(new java.awt.Color(204, 255, 255));
        btnRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/retroceder.png"))); // NOI18N
        btnRetroceder.setText("Retroceder");
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/imagen_fondo.png"))); // NOI18N
        lblfondo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        // TODO add your handling code here:
        // Obtener los valores de los campos
        String nombre = txtNombre.getText();
        String id = txtID.getText();
        String fecha = txtFecha.getText();
        String hora = txtHora.getText();
        String periodo = cboPeriodo.getSelectedItem().toString(); // AM o PM
        String motivo = cboMotivo.getSelectedItem().toString();

        // Validar que no haya campos vacíos
        if (nombre.isEmpty() || id.isEmpty() || fecha.isEmpty() || hora.isEmpty() || motivo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
            return;
        }

        // Validar formato de la fecha (dd/MM/yyyy)
        if (!fecha.matches("\\d{2}/\\d{2}/\\d{4}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Usa el formato DD/MM/AAAA (ejemplo: 05/11/2025).");
            return;
        }

        // Validar formato de la hora (hh:mm en 12 horas)
        // Solo permite horas de 01 a 12 y minutos de 00 a 59
        if (!hora.matches("^(0?[1-9]|1[0-2]):[0-5][0-9]$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Formato de hora inválido. Usa el formato hh:mm (ejemplo: 03:45).");
            return;
        }
        
        // Combinar la hora con el periodo AM o PM
        String horaCompleta = hora + " " + periodo;
        
        // validar citas entre las horas 6 AM y PM
        try {
        // Extraer la hora en número (parte antes de ":")
        int horaNumero = Integer.parseInt(hora.split(":")[0]);

        // Validar el rango según AM o PM
        if ((periodo.equals("AM") && horaNumero < 6) || (periodo.equals("PM") && horaNumero > 6)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Solo se permiten citas entre las 6 AM y las 6 PM.");
            return;
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Formato de hora inválido. Usa el formato hh:mm (ejemplo: 03:45).");
        return;
    }
        
        // Validar que la fecha no sea anterior a la actual
    try {
        java.text.SimpleDateFormat formato = new java.text.SimpleDateFormat("dd/MM/yyyy");
        formato.setLenient(false); // No permite fechas inválidas como 32/01/2025
        java.util.Date fechaIngresada = formato.parse(fecha);
        java.util.Date fechaActual = new java.util.Date();

        if (fechaIngresada.before(fechaActual)) {
            javax.swing.JOptionPane.showMessageDialog(this, "No puedes agendar citas en fechas pasadas.");
            return;
        }
    } catch (java.text.ParseException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Fecha inválida. Usa el formato DD/MM/AAAA (ejemplo: 05/11/2025).");
        return;
    }
        
        // Validar si ya existe una cita el mismo día y hora
        try {
            File archivo = new File("baseDeDatos/citas.csv"); // Ruta del archivo donde se guardan las citas
            if (archivo.exists()) { // Solo verifica si el archivo ya existe
                try (Scanner lector = new Scanner(archivo)) { // Permite leer línea por línea el archivo CSV
                    while (lector.hasNextLine()) { // Recorre cada línea (cada cita guardada)
                        String linea = lector.nextLine(); // Lee una línea completa
                        String[] datos = linea.split(","); // Separa los valores por coma (,)
                        if (datos.length >= 4) { // Verifica que haya al menos 4 columnas: nombre, id, fecha, hora
                            String fechaGuardada = datos[2]; // Columna 3 → fecha
                            String horaGuardada = datos[3]; // Columna 4 → hora
                            if (fecha.equals(fechaGuardada) && horaCompleta.equals(horaGuardada)) { // Si la fecha y hora ya existen, no se puede agendar
                                javax.swing.JOptionPane.showMessageDialog(this, "Ya existe una cita registrada el " + fecha + " a las " + hora + ". Por favor, elige otra hora o día.");
                                lector.close(); // Cierra el lector del archivo
                                return; // Detiene el proceso para no duplicar la cita
                            }
                        }
                    }
                }
            }
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al verificar citas existentes.");
            return;
    }

        // Intentar guardar los datos en el archivo CSV
        try {
            try (FileWriter guardar = new FileWriter("baseDeDatos/citas.csv", true)) {
                guardar.write(nombre + "," + id + "," + fecha + "," + horaCompleta + "," + motivo + "\n");
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Cita registrada correctamente.");

            // Limpiar los campos después de guardar
            txtNombre.setText("");
            txtID.setText("");
            txtFecha.setText("DD/MM/AAAA");
            txtHora.setText("HH:MM");
            cboPeriodo.setSelectedIndex(0);
            cboMotivo.setSelectedIndex(0);

        } catch (IOException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar la cita.");
        }
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void txtIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKeyPressed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        // Limpiar los campos después de guardar
            txtNombre.setText("");
            txtID.setText("");
            txtFecha.setText("DD/MM/AAAA");
            txtHora.setText("HH:MM");
            cboPeriodo.setSelectedIndex(0);
            cboMotivo.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        // TODO add your handling code here:
        interfaz_clienteCatagalo catalogo = new interfaz_clienteCatagalo();
        catalogo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRetrocederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Agendar_cita_cliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JComboBox<String> cboMotivo;
    private javax.swing.JComboBox<String> cboPeriodo;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
