/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package concesionarioapp;

import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author User
 */
public class CrearCuenta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearCuenta.class.getName());

    /**
     * Creates new form CrearCuenta
     */
    public CrearCuenta() {
        initComponents();
        lblCodigo.setVisible(false);
        txtCodigo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        cboTipoUsuario = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        guardarDatos = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        btnRetroceder = new javax.swing.JButton();
        lbllogo = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 75, -1, -1));

        lblApellido.setForeground(new java.awt.Color(0, 0, 0));
        lblApellido.setText("Apellido");
        getContentPane().add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 120, -1, -1));

        lblNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreUsuario.setText("Nombre de usuario");
        getContentPane().add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 168, -1, -1));

        lblContraseña.setForeground(new java.awt.Color(0, 0, 0));
        lblContraseña.setText("Contraseña");
        getContentPane().add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 213, -1, -1));

        cboTipoUsuario.setBackground(new java.awt.Color(51, 153, 255));
        cboTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Administrador" }));
        cboTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(cboTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 272, 30));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 75, 138, -1));

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 210, 138, -1));

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 120, 138, -1));

        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 165, 138, -1));

        guardarDatos.setBackground(new java.awt.Color(51, 153, 255));
        guardarDatos.setText("Crear Cuenta");
        guardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(guardarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        lblCodigo.setBackground(new java.awt.Color(0, 0, 0));
        lblCodigo.setForeground(new java.awt.Color(0, 0, 0));
        lblCodigo.setText("Código administrador");
        getContentPane().add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        btnRetroceder.setBackground(new java.awt.Color(51, 102, 255));
        btnRetroceder.setForeground(new java.awt.Color(255, 255, 255));
        btnRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/retroceder.png"))); // NOI18N
        btnRetroceder.setText(" Retroceder");
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/fondo1.png"))); // NOI18N
        getContentPane().add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 100, 60));

        lblfondo.setBackground(new java.awt.Color(0, 0, 0));
        lblfondo.setForeground(new java.awt.Color(0, 0, 0));
        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/imagen_fondo.png"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 500));

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 299, 138, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void guardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarDatosActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String NombreUsuario = txtNombreUsuario.getText();
        String Contraseña = txtContraseña.getText();
        String tipoUsuario = cboTipoUsuario.getSelectedItem().toString();
        String Codigo = txtCodigo.getText();
        String codigoSeguridad = "3067863";
        
        if (nombre.isEmpty() || apellido.isEmpty() || NombreUsuario.isEmpty() || Contraseña.isEmpty() || tipoUsuario.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
        }
        if (tipoUsuario.equals("Administrador")){
            
            if (Codigo.isEmpty()){
                javax.swing.JOptionPane.showMessageDialog(this, "Debes ingresar el código de seguridad para administrador.");
                return;
            }
            if(!Codigo.equals(codigoSeguridad)){
                javax.swing.JOptionPane.showMessageDialog(this, "Código de seguridad incorrecto. No puedes crear cuenta de administrador.");
                return;
            }
            try {
                FileWriter guardar = new FileWriter("baseDeDatos/usuarios.csv", true); // guarda en archivo del proyecto
                guardar.write(NombreUsuario + "," + Contraseña + "," + tipoUsuario + "\n");
                guardar.close();
                
                javax.swing.JOptionPane.showMessageDialog(this, "Cuenta de ADMINISTRADOR creada y guardada correctamente.");
                
                InicioApp inicioApp = new InicioApp();
                inicioApp.setVisible(true);
                this.dispose();
                
            } catch (IOException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar el usuario.");
        }        
        }
        else{
            try {
                FileWriter guardar = new FileWriter("baseDeDatos/usuarios.csv", true);
                guardar.write(NombreUsuario + "," + Contraseña + "," + tipoUsuario + "\n");
                guardar.close();
                
                javax.swing.JOptionPane.showMessageDialog(this, "Cuenta de CLIENTE creada y guardada correctamente.");
                
                InicioApp inicioApp = new InicioApp();
                inicioApp.setVisible(true);
                this.dispose();
                
            } catch (IOException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar el usuario.");
            }
        }
    }//GEN-LAST:event_guardarDatosActionPerformed

    private void cboTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoUsuarioActionPerformed
        // TODO add your handling code here:
        String tipoUsuario = cboTipoUsuario.getSelectedItem().toString();
        
        if (tipoUsuario.equals("Administrador")) {
            lblCodigo.setVisible(true);
            txtCodigo.setVisible(true);
        } 
        else {
            lblCodigo.setVisible(false);
            txtCodigo.setVisible(false);
    }
    }//GEN-LAST:event_cboTipoUsuarioActionPerformed

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        // TODO add your handling code here:
        InicioApp inicioApp = new InicioApp();
        inicioApp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRetrocederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CrearCuenta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JComboBox<String> cboTipoUsuario;
    private javax.swing.JButton guardarDatos;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
