/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package concesionarioapp;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author Reverie Pink
 */
public class gestionar_vehiculos extends javax.swing.JFrame {
    
    
    private String rutaImagenSeleccionada = "";
    

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(gestionar_vehiculos.class.getName());

    /**
     * Creates new form gestionar_vehiculos
     */
    public gestionar_vehiculos() {
        initComponents();
        jScrollPane1.setViewportView(jPanel2); 
        cargarCatalogo();
        
        if (cboFiltro.getSelectedItem() != null && 
            cboFiltro.getSelectedItem().toString().equalsIgnoreCase("Todo")) {
            txtFiltro.setVisible(false);
        } else {
            txtFiltro.setVisible(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblmarca = new javax.swing.JLabel();
        txtmodelo = new javax.swing.JTextField();
        lblaño = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        lblmodelo1 = new javax.swing.JLabel();
        lbldescripcion = new javax.swing.JLabel();
        lblprecio = new javax.swing.JLabel();
        txtaño = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        btnimagen = new javax.swing.JButton();
        lblvista = new javax.swing.JLabel();
        txtNombreProp = new javax.swing.JTextField();
        txtCedulaProp = new javax.swing.JTextField();
        txtTelefonoProp = new javax.swing.JTextField();
        txtDireccionProp = new javax.swing.JTextField();
        txtEmailProp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKilometraje = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        btnguardarvehiculo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        btnactualizarcatalogo = new javax.swing.JButton();
        btnRetroceder = new javax.swing.JButton();
        lblFiltro = new javax.swing.JLabel();
        cboFiltro = new javax.swing.JComboBox<>();
        txtFiltro = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Vehículo"));

        lblmarca.setText("Marca");

        lblaño.setText("Año");

        lblmodelo1.setText("Modelo");

        lbldescripcion.setText("Descripcion");

        lblprecio.setText("Precio");

        btnimagen.setText("Seleccionar imagen");
        btnimagen.setBorder(null);
        btnimagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimagenActionPerformed(evt);
            }
        });

        lblvista.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setText("Nombre propietario");

        jLabel2.setText("Cedula");

        jLabel3.setText("Telefono");

        jLabel4.setText("Dirección");

        jLabel5.setText("E-mail");

        jLabel6.setText("Kilometraje");

        jLabel7.setText("Placa");

        btnguardarvehiculo.setText("Guardar Vehículo");
        btnguardarvehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarvehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblvista, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblprecio)
                                        .addComponent(lblaño)
                                        .addComponent(lblmodelo1)
                                        .addComponent(lblmarca)
                                        .addComponent(lbldescripcion)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addGap(42, 42, 42)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPlaca)
                                        .addComponent(txtKilometraje)
                                        .addComponent(txtprecio)
                                        .addComponent(txtdescripcion)
                                        .addComponent(txtaño)
                                        .addComponent(txtmodelo)
                                        .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtTelefonoProp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                        .addComponent(txtDireccionProp, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEmailProp, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCedulaProp, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(txtNombreProp, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnguardarvehiculo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmarca)
                    .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmodelo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblaño))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblprecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldescripcion)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(btnimagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblvista, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCedulaProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(btnguardarvehiculo)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 730));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Catalogo Vehículos"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 101, 820, 500));

        btnactualizarcatalogo.setBackground(new java.awt.Color(51, 153, 255));
        btnactualizarcatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/actualizar.png"))); // NOI18N
        btnactualizarcatalogo.setText("Actualizar Catálogo");
        btnactualizarcatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarcatalogoActionPerformed(evt);
            }
        });
        getContentPane().add(btnactualizarcatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 610, -1, -1));

        btnRetroceder.setBackground(new java.awt.Color(153, 204, 255));
        btnRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/retroceder.png"))); // NOI18N
        btnRetroceder.setText("Retroceder");
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, -1));

        lblFiltro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFiltro.setText("Filtro");
        getContentPane().add(lblFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 610, 60, -1));

        cboFiltro.setBackground(new java.awt.Color(102, 204, 255));
        cboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todo", "Marca", "Modelo", "Año", "Precio" }));
        cboFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFiltroActionPerformed(evt);
            }
        });
        getContentPane().add(cboFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 650, -1, -1));

        txtFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroActionPerformed(evt);
            }
        });
        getContentPane().add(txtFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 680, 130, -1));

        btnFiltrar.setBackground(new java.awt.Color(204, 255, 255));
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 710, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/fondo1.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 110, 70));

        btnEditar.setText("Editar");
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 680, 90, -1));

        btnEliminar.setText("Eliminar");
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 680, -1, -1));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/imagen_fondo.png"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void cargarCatalogo() {
    jPanel2.removeAll();

    java.io.File archivo = new java.io.File("baseDeDatos/coches.csv");
    if (!archivo.exists()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay vehículos guardados todavía.");
        return;
    }

    try (var br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
        String linea;
        int y = 10;

        // Saltar encabezado si lo hay
        br.readLine();

        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(",");

            if (datos.length == 5) {
                javax.swing.JPanel item = new javax.swing.JPanel();
                item.setLayout(new javax.swing.BoxLayout(item, javax.swing.BoxLayout.Y_AXIS));
                item.setBorder(javax.swing.BorderFactory.createTitledBorder(datos[0] + " - " + datos[1]));

                item.add(new javax.swing.JLabel("Año: " + datos[2]));
                item.add(new javax.swing.JLabel("Precio: " + datos[3]));
                item.add(new javax.swing.JLabel("Descripción: " + datos[4]));

                item.setBounds(10, y, 400, 90);
                y += 100;
                jPanel2.add(item);
            }
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar el catálogo: " + e.getMessage());
    }

    jPanel2.revalidate();
    jPanel2.repaint();
}

    
    
    
    
    private void btnguardarvehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarvehiculoActionPerformed
        // TODO add your handling code here:
String marca = txtmarca.getText().trim();
    String modelo = txtmodelo.getText().trim();
    String año = txtaño.getText().trim();
    String precio = txtprecio.getText().trim();
    String kilometraje = txtKilometraje.getText().trim();
    String descripcion = txtdescripcion.getText().trim();
    String placa = txtPlaca.getText().trim();

    // Estos vienen del propietario
    String nombreProp = txtNombreProp.getText().trim();
    String cedulaProp = txtCedulaProp.getText().trim();
    String telefonoProp = txtTelefonoProp.getText().trim();
    String direccionProp = txtDireccionProp.getText().trim();
    String emailProp = txtEmailProp.getText().trim();

    // Ruta de imagen (guardada por tu botón aparte)
    if (rutaImagenSeleccionada == null || rutaImagenSeleccionada.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor selecciona una imagen del vehículo.");
        return;
    }

    // Validar campos vacíos
    if (marca.isEmpty() || modelo.isEmpty() || año.isEmpty() || precio.isEmpty() || descripcion.isEmpty()
            || placa.isEmpty() || nombreProp.isEmpty() || cedulaProp.isEmpty() || telefonoProp.isEmpty()
            || direccionProp.isEmpty() || emailProp.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor completa todos los campos antes de guardar.");
        return;
    }

    try {
        File archivo = new File("baseDeDatos/coches.csv");
        boolean nuevo = !archivo.exists();

        FileWriter fw = new FileWriter(archivo, true);
        BufferedWriter bw = new BufferedWriter(fw);

        if (nuevo) {
            bw.write("marca,modelo,año,precio,kilometraje,descripcion,placa,imagen,nombreProp,cedulaProp,telefonoProp,direccionProp,emailProp");
            bw.newLine();
        }

        bw.write(marca + "," + modelo + "," + año + "," + precio + "," + kilometraje + "," + descripcion + "," +
                 placa + "," + rutaImagenSeleccionada + "," + nombreProp + "," + cedulaProp + "," + telefonoProp + "," +
                 direccionProp + "," + emailProp);
        bw.newLine();

        bw.close();
        fw.close();

        JOptionPane.showMessageDialog(this, "Vehículo guardado correctamente.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
    }
        

    }//GEN-LAST:event_btnguardarvehiculoActionPerformed

    private void btnactualizarcatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarcatalogoActionPerformed
        // TODO add your handling code here:
     jPanel2.removeAll();
    jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));
    jPanel2.setBackground(new Color(240, 240, 240)); // fondo gris claro

    try (BufferedReader br = new BufferedReader(new FileReader("baseDeDatos/coches.csv"))) {
        String linea;
        br.readLine(); // Saltar encabezado
        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(",");
            if (datos.length < 13) continue;

            // Datos
            String marca = datos[0];
            String modelo = datos[1];
            String año = datos[2];
            String precio = datos[3];
            String kilometraje = datos[4];
            String descripcion = datos[5];
            String placa = datos[6];
            String rutaImagen = datos[7];
            String nombreProp = datos[8];
            String cedulaProp = datos[9];
            String telefonoProp = datos[10];
            String direccionProp = datos[11];
            String emailProp = datos[12];

            // Panel individual
            JPanel panelVehiculo = new JPanel(new BorderLayout(10, 10));
            panelVehiculo.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(180, 180, 180), 1, true),
                BorderFactory.createEmptyBorder(10, 10, 10, 10)
            ));
            panelVehiculo.setBackground(Color.WHITE);
            panelVehiculo.setPreferredSize(new Dimension(450, 230));
            panelVehiculo.setMaximumSize(new Dimension(450, 230));

            // Imagen
            JLabel lblImagen = new JLabel();
            lblImagen.setPreferredSize(new Dimension(140, 100));
            try {
                ImageIcon icon = new ImageIcon(rutaImagen);
                Image img = icon.getImage().getScaledInstance(130, 90, Image.SCALE_SMOOTH);
                lblImagen.setIcon(new ImageIcon(img));
            } catch (Exception e) {
                lblImagen.setText("Sin imagen");
            }

            // Texto del vehículo
            JTextArea txtInfoVehiculo = new JTextArea(
                "Marca: " + marca + "\n" +
                "Modelo: " + modelo + "\n" +
                "Año: " + año + "\n" +
                "Precio: " + precio + "\n" +
                "Kilometraje: " + kilometraje + "\n" +
                "Descripción: " + descripcion + "\n" +
                "Placa: " + placa
            );
            txtInfoVehiculo.setEditable(false);
            txtInfoVehiculo.setBackground(Color.WHITE);
            txtInfoVehiculo.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));

            // Texto del propietario
            JTextArea txtInfoProp = new JTextArea(
                "Propietario: " + nombreProp + "\n" +
                "Cédula: " + cedulaProp + "\n" +
                "Teléfono: " + telefonoProp + "\n" +
                "Dirección: " + direccionProp + "\n" +
                "Email: " + emailProp
            );
            txtInfoProp.setEditable(false);
            txtInfoProp.setBackground(Color.WHITE);
            txtInfoProp.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));

            // Combinar textos
            JPanel panelTexto = new JPanel(new GridLayout(2, 1, 0, 5));
            panelTexto.setBackground(Color.WHITE);
            panelTexto.add(txtInfoVehiculo);
            panelTexto.add(txtInfoProp);

            // Ensamblar panel
            panelVehiculo.add(lblImagen, BorderLayout.WEST);
            panelVehiculo.add(panelTexto, BorderLayout.CENTER);

            // Agregar al contenedor
            jPanel2.add(panelVehiculo);
            jPanel2.add(Box.createVerticalStrut(15)); // 🔹 Espacio entre tarjetas (~1 cm)
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al leer el catálogo: " + e.getMessage());
    }

    jPanel2.revalidate();
    jPanel2.repaint(); 
       
    }//GEN-LAST:event_btnactualizarcatalogoActionPerformed

    private void btnimagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimagenActionPerformed
        // TODO add your handling code here:
        
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
    chooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
    chooser.setDialogTitle("Seleccionar imagen del vehículo");

    // Filtro solo para imágenes
    chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imágenes", "jpg", "jpeg", "png"));

    int resultado = chooser.showOpenDialog(this);
    if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File archivoSeleccionado = chooser.getSelectedFile();

        // Carpeta destino
        java.io.File carpetaImagenes = new java.io.File("imagenes");
        if (!carpetaImagenes.exists()) {
            carpetaImagenes.mkdirs();
        }

        // Copiar la imagen al proyecto
        String nombreArchivo = archivoSeleccionado.getName();
        java.io.File destino = new java.io.File(carpetaImagenes, nombreArchivo);

        try {
            java.nio.file.Files.copy(
                archivoSeleccionado.toPath(),
                destino.toPath(),
                java.nio.file.StandardCopyOption.REPLACE_EXISTING
            );
            rutaImagenSeleccionada = "imagenes/" + nombreArchivo;

            // Mostrar vista previa
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
                new javax.swing.ImageIcon(rutaImagenSeleccionada)
                    .getImage()
                    .getScaledInstance(120, 80, java.awt.Image.SCALE_SMOOTH)
            );
            lblvista.setIcon(icon);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al copiar la imagen: " + e.getMessage());
        }
    }
        
        
    }//GEN-LAST:event_btnimagenActionPerformed

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        // TODO add your handling code here:
        new interfaz_administrador().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRetrocederActionPerformed

    private void cboFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFiltroActionPerformed
        // TODO add your handling code here:
        String seleccion = "";
    if (cboFiltro.getSelectedItem() != null) {
        seleccion = cboFiltro.getSelectedItem().toString().trim();
    }

    if (seleccion.equalsIgnoreCase("Todo")) {
        txtFiltro.setVisible(false);
        txtFiltro.setText("");
    } else {
        txtFiltro.setVisible(true);
        txtFiltro.setText("");
        txtFiltro.requestFocusInWindow();
    }

    // Forzamos actualización del layout por si el GroupLayout no refresca solo
    if (txtFiltro.getParent() != null) {
        txtFiltro.getParent().revalidate();
        txtFiltro.getParent().repaint();
    }
    }//GEN-LAST:event_cboFiltroActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
     // 🔹 Limpiar y configurar el panel antes de mostrar resultados
jPanel2.removeAll();
jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));
jPanel2.setBackground(new Color(240, 240, 240));

// 🔹 Obtener filtro seleccionado y texto ingresado
String filtro = cboFiltro.getSelectedItem().toString();
String valor = txtFiltro.getText().trim().toLowerCase();

// 🔹 Validación de campo vacío
if (!filtro.equalsIgnoreCase("Todo")) {
    if (valor.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Por favor ingrese un valor para filtrar.",
            "Campo vacío",
            JOptionPane.WARNING_MESSAGE);
        return; // Detener ejecución si está vacío
    }
}

// Contador para saber si se encontró al menos un resultado
int contador = 0;

try (BufferedReader br = new BufferedReader(new FileReader("baseDeDatos/coches.csv"))) {
    String linea = br.readLine(); // Saltar encabezado

    while ((linea = br.readLine()) != null) {
        String[] datos = linea.split(",");
        if (datos.length < 13) continue; // Saltar líneas incompletas

        // 🔹 Asignación de datos
        String marca = datos[0];
        String modelo = datos[1];
        String año = datos[2];
        String precio = datos[3];
        String kilometraje = datos[4];
        String descripcion = datos[5];
        String placa = datos[6];
        String rutaImagen = datos[7];
        String nombreProp = datos[8];
        String cedulaProp = datos[9];
        String telefonoProp = datos[10];
        String direccionProp = datos[11];
        String emailProp = datos[12];

        boolean coincide = false;

        // 🔹 Filtrar según selección
        if (filtro.equals("Todo")) {
            coincide = true;
        } else if (filtro.equals("Marca") && marca.toLowerCase().contains(valor)) {
            coincide = true;
        } else if (filtro.equals("Modelo") && modelo.toLowerCase().contains(valor)) {
            coincide = true;
        } else if (filtro.equals("Año") && año.toLowerCase().contains(valor)) {
            coincide = true;
        } else if (filtro.equals("Precio") && precio.toLowerCase().contains(valor)) {
            coincide = true;
        }

        // 🔹 Si coincide, crear panel con la información
        if (coincide) {
            JPanel panelVehiculo = new JPanel(new BorderLayout(10, 10));
            panelVehiculo.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(180, 180, 180), 1, true),
                BorderFactory.createEmptyBorder(10, 10, 10, 10)
            ));
            panelVehiculo.setBackground(Color.WHITE);
            panelVehiculo.setPreferredSize(new Dimension(450, 230));
            panelVehiculo.setMaximumSize(new Dimension(450, 230));

            // Imagen del vehículo
            JLabel lblImagen = new JLabel();
            lblImagen.setPreferredSize(new Dimension(140, 100));
            try {
                ImageIcon icon = new ImageIcon(rutaImagen);
                Image img = icon.getImage().getScaledInstance(130, 90, Image.SCALE_SMOOTH);
                lblImagen.setIcon(new ImageIcon(img));
            } catch (Exception e) {
                lblImagen.setText("Sin imagen");
            }

            // Datos del vehículo
            JTextArea txtInfoVehiculo = new JTextArea(
                "Marca: " + marca + "\n" +
                "Modelo: " + modelo + "\n" +
                "Año: " + año + "\n" +
                "Precio: " + precio + "\n" +
                "Kilometraje: " + kilometraje + "\n" +
                "Descripción: " + descripcion + "\n" +
                "Placa: " + placa
            );
            txtInfoVehiculo.setEditable(false);
            txtInfoVehiculo.setBackground(Color.WHITE);
            txtInfoVehiculo.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));

            // Datos del propietario
            JTextArea txtInfoProp = new JTextArea(
                "Propietario: " + nombreProp + "\n" +
                "Cédula: " + cedulaProp + "\n" +
                "Teléfono: " + telefonoProp + "\n" +
                "Dirección: " + direccionProp + "\n" +
                "Email: " + emailProp
            );
            txtInfoProp.setEditable(false);
            txtInfoProp.setBackground(Color.WHITE);
            txtInfoProp.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));

            // Panel interno de texto
            JPanel panelTexto = new JPanel(new GridLayout(2, 1, 0, 5));
            panelTexto.setBackground(Color.WHITE);
            panelTexto.add(txtInfoVehiculo);
            panelTexto.add(txtInfoProp);

            // Ensamblar panel final
            panelVehiculo.add(lblImagen, BorderLayout.WEST);
            panelVehiculo.add(panelTexto, BorderLayout.CENTER);

            jPanel2.add(panelVehiculo);
            jPanel2.add(Box.createRigidArea(new Dimension(0, 10)));

            contador++;
        }
    }

    // 🔹 Si no hay resultados, mostrar mensaje
    if (contador == 0) {
        JOptionPane.showMessageDialog(this,
            "No se encontraron resultados con el filtro seleccionado.",
            "Sin resultados",
            JOptionPane.INFORMATION_MESSAGE);

        JLabel lblVacio = new JLabel("No se encontraron vehículos con ese filtro.");
        lblVacio.setAlignmentX(CENTER_ALIGNMENT);
        jPanel2.add(lblVacio);
    }

    // 🔹 Actualizar panel visualmente
    jPanel2.revalidate();
    jPanel2.repaint();

} catch (IOException e) {
    JOptionPane.showMessageDialog(this, "Error al filtrar: " + e.getMessage());
}
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void txtFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new gestionar_vehiculos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JButton btnactualizarcatalogo;
    private javax.swing.JButton btnguardarvehiculo;
    private javax.swing.JButton btnimagen;
    private javax.swing.JComboBox<String> cboFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JLabel lblaño;
    private javax.swing.JLabel lbldescripcion;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblmarca;
    private javax.swing.JLabel lblmodelo1;
    private javax.swing.JLabel lblprecio;
    private javax.swing.JLabel lblvista;
    private javax.swing.JTextField txtCedulaProp;
    private javax.swing.JTextField txtDireccionProp;
    private javax.swing.JTextField txtEmailProp;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JTextField txtKilometraje;
    private javax.swing.JTextField txtNombreProp;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtTelefonoProp;
    private javax.swing.JTextField txtaño;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
