/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package concesionarioapp;

/**
 *
 * @author Reverie Pink
 */
public class gestionar_vehiculos extends javax.swing.JFrame {
    
    private String rutaImagenSeleccionada = "";

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(gestionar_vehiculos.class.getName());

    /**
     * Creates new form gestionar_vehiculos
     */
    public gestionar_vehiculos() {
        initComponents();
        jScrollPane1.setViewportView(jPanel2); 
        cargarCatalogo();
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblmarca = new javax.swing.JLabel();
        txtmodelo = new javax.swing.JTextField();
        lblaño = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        lblmodelo1 = new javax.swing.JLabel();
        lbldescripcion = new javax.swing.JLabel();
        lblprecio = new javax.swing.JLabel();
        txtaño = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        btnguardarvehiculo = new javax.swing.JButton();
        btnimagen = new javax.swing.JButton();
        lblvista = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        btnactualizarcatalogo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Vehículo"));

        lblmarca.setText("Marca");

        lblaño.setText("Año");

        lblmodelo1.setText("Modelo");

        lbldescripcion.setText("Descripcion");

        lblprecio.setText("Precio");

        btnguardarvehiculo.setText("Guardar Vehículo");
        btnguardarvehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarvehiculoActionPerformed(evt);
            }
        });

        btnimagen.setText("Seleccionar imagen");
        btnimagen.setBorder(null);
        btnimagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimagenActionPerformed(evt);
            }
        });

        lblvista.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblprecio)
                    .addComponent(lblaño)
                    .addComponent(lblmodelo1)
                    .addComponent(lblmarca)
                    .addComponent(lbldescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtaño, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblvista, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnguardarvehiculo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmarca)
                    .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmodelo1)
                    .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblaño)
                    .addComponent(txtaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblprecio)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldescripcion)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(btnimagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblvista, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnguardarvehiculo)
                .addGap(25, 25, 25))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Catalogo Vehículos"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        btnactualizarcatalogo.setText("Actualizar Catálogo");
        btnactualizarcatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarcatalogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnactualizarcatalogo)
                .addGap(499, 499, 499))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnactualizarcatalogo)
                .addGap(514, 514, 514))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void cargarCatalogo() {
    jPanel2.removeAll();

    java.io.File archivo = new java.io.File("baseDeDatos/coches.csv");
    if (!archivo.exists()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay vehículos guardados todavía.");
        return;
    }

    try (var br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
        String linea;
        int y = 10;

        // Saltar encabezado si lo hay
        br.readLine();

        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(",");

            if (datos.length == 5) {
                javax.swing.JPanel item = new javax.swing.JPanel();
                item.setLayout(new javax.swing.BoxLayout(item, javax.swing.BoxLayout.Y_AXIS));
                item.setBorder(javax.swing.BorderFactory.createTitledBorder(datos[0] + " - " + datos[1]));

                item.add(new javax.swing.JLabel("Año: " + datos[2]));
                item.add(new javax.swing.JLabel("Precio: " + datos[3]));
                item.add(new javax.swing.JLabel("Descripción: " + datos[4]));

                item.setBounds(10, y, 400, 90);
                y += 100;
                jPanel2.add(item);
            }
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar el catálogo: " + e.getMessage());
    }

    jPanel2.revalidate();
    jPanel2.repaint();
}

    
    
    
    
    private void btnguardarvehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarvehiculoActionPerformed
        // TODO add your handling code here:
    String marca = txtmarca.getText().trim();
    String modelo = txtmodelo.getText().trim();
    String año = txtaño.getText().trim();
    String precio = txtprecio.getText().trim();
    String descripcion = txtdescripcion.getText().trim();

    if (marca.isEmpty() || modelo.isEmpty() || año.isEmpty() || precio.isEmpty() || descripcion.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llena todos los campos.");
        return;
    }

    try {
        java.io.File archivo = new java.io.File("baseDeDatos/coches.csv");
        boolean archivoNuevo = !archivo.exists();

        java.io.FileWriter fw = new java.io.FileWriter(archivo, true);
        java.io.BufferedWriter bw = new java.io.BufferedWriter(fw);

        if (archivoNuevo) {
            bw.write("Marca,Modelo,Año,Precio,Descripción");
            bw.newLine();
        }

        bw.write(marca + "," + modelo + "," + año + "," + precio + "," + descripcion + "," + rutaImagenSeleccionada);
        bw.newLine();
        bw.close();
        fw.close();

        txtmarca.setText("");
        txtmodelo.setText("");
        txtaño.setText("");
        txtprecio.setText("");
        txtdescripcion.setText("");

        javax.swing.JOptionPane.showMessageDialog(this, "Vehículo añadido y guardado correctamente.");

        // Cargar automáticamente el nuevo catálogo
        cargarCatalogo();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar en CSV: " + e.getMessage());
    }
    }//GEN-LAST:event_btnguardarvehiculoActionPerformed

    private void btnactualizarcatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarcatalogoActionPerformed
        // TODO add your handling code here:
        
        jPanel2.removeAll(); // Limpia los paneles anteriores

         java.io.File archivo = new java.io.File("baseDeDatos/coches.csv");
          if (!archivo.exists()) {
              javax.swing.JOptionPane.showMessageDialog(this, "No hay vehículos guardados todavía.");
                  return;
    }

    try (var br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
        String linea;
        int y = 10;

        // Saltar la cabecera
        br.readLine();

        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(",");

            //6 columnas (Marca, Modelo, Año, Precio, Descripción, Imagen)
            if (datos.length >= 6) {
                javax.swing.JPanel item = new javax.swing.JPanel();
                item.setLayout(null);
                item.setBorder(javax.swing.BorderFactory.createTitledBorder(datos[0] + " - " + datos[1]));
                item.setBounds(10, y, 500, 120);

                // Texto
                javax.swing.JLabel lblAnio = new javax.swing.JLabel("Año: " + datos[2]);
                lblAnio.setBounds(140, 20, 200, 20);
                item.add(lblAnio);

                javax.swing.JLabel lblPrecio = new javax.swing.JLabel("Precio: " + datos[3]);
                lblPrecio.setBounds(140, 40, 200, 20);
                item.add(lblPrecio);

                javax.swing.JLabel lblDescripcion = new javax.swing.JLabel("<html>Descripción: " + datos[4] + "</html>");
                lblDescripcion.setBounds(140, 60, 300, 40);
                item.add(lblDescripcion);

                // Imagen
                String rutaImagen = datos[5];
                if (!rutaImagen.isEmpty()) {
                    javax.swing.ImageIcon icono = new javax.swing.ImageIcon(
                        new javax.swing.ImageIcon(rutaImagen).getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH)
                    );
                    javax.swing.JLabel lblImagen = new javax.swing.JLabel(icono);
                    lblImagen.setBounds(10, 20, 100, 80);
                    item.add(lblImagen);
                }

                jPanel2.add(item);
                y += 130;
            }
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar el catálogo: " + e.getMessage());
    }

    jPanel2.revalidate();
    jPanel2.repaint();

    }//GEN-LAST:event_btnactualizarcatalogoActionPerformed

    private void btnimagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimagenActionPerformed
        // TODO add your handling code here:
        
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
    chooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
    chooser.setDialogTitle("Seleccionar imagen del vehículo");

    // Filtro solo para imágenes
    chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imágenes", "jpg", "jpeg", "png"));

    int resultado = chooser.showOpenDialog(this);
    if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File archivoSeleccionado = chooser.getSelectedFile();

        // Carpeta destino
        java.io.File carpetaImagenes = new java.io.File("imagenes");
        if (!carpetaImagenes.exists()) {
            carpetaImagenes.mkdirs();
        }

        // Copiar la imagen al proyecto
        String nombreArchivo = archivoSeleccionado.getName();
        java.io.File destino = new java.io.File(carpetaImagenes, nombreArchivo);

        try {
            java.nio.file.Files.copy(
                archivoSeleccionado.toPath(),
                destino.toPath(),
                java.nio.file.StandardCopyOption.REPLACE_EXISTING
            );
            rutaImagenSeleccionada = "imagenes/" + nombreArchivo;

            // Mostrar vista previa
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
                new javax.swing.ImageIcon(rutaImagenSeleccionada)
                    .getImage()
                    .getScaledInstance(120, 80, java.awt.Image.SCALE_SMOOTH)
            );
            lblvista.setIcon(icon);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al copiar la imagen: " + e.getMessage());
        }
    }
        
        
    }//GEN-LAST:event_btnimagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new gestionar_vehiculos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizarcatalogo;
    private javax.swing.JButton btnguardarvehiculo;
    private javax.swing.JButton btnimagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblaño;
    private javax.swing.JLabel lbldescripcion;
    private javax.swing.JLabel lblmarca;
    private javax.swing.JLabel lblmodelo1;
    private javax.swing.JLabel lblprecio;
    private javax.swing.JLabel lblvista;
    private javax.swing.JTextField txtaño;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
