package concesionarioapp;

import concesionarioapp.interfaz_administrador;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Reverie Pink
 */
public class gestionar_citas_admin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(gestionar_citas_admin.class.getName());

    /**
     * Creates new form gestionar_citas_admin
     */
    public gestionar_citas_admin() {
        initComponents();
        setLocationRelativeTo(null);
        cargarCitasEnTabla();
    }
    
    private void cargarCitasEnTabla() {
    DefaultTableModel modelo = (DefaultTableModel) tablacitas.getModel();
    modelo.setRowCount(0); // Limpia la tabla antes de cargar

    try (BufferedReader br = new BufferedReader(new FileReader("baseDeDatos/citas.csv"))) {
        String linea;
        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(",");
            if (datos.length >= 5) {
                modelo.addRow(datos);
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al leer las citas: " + e.getMessage());
    }
}

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacitas = new javax.swing.JTable();
        btnactualizar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnRetroceder = new javax.swing.JButton();
        lbllogo = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablacitas.setBackground(new java.awt.Color(153, 204, 255));
        tablacitas.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));
        tablacitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Cedula", "Fecha", "Hora", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(tablacitas);

        jScrollPane2.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 76, 621, 558));

        btnactualizar.setBackground(new java.awt.Color(153, 204, 255));
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/actualizar.png"))); // NOI18N
        btnactualizar.setText("Actualizar ");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 111, 139, -1));

        btneditar.setBackground(new java.awt.Color(255, 255, 153));
        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/editar.png"))); // NOI18N
        btneditar.setText("Editar citas");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        getContentPane().add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 185, 139, -1));

        btncancelar.setBackground(new java.awt.Color(255, 153, 153));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/cancelar.png"))); // NOI18N
        btncancelar.setText("Cancelar cita");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 256, -1, -1));

        btnRetroceder.setBackground(new java.awt.Color(153, 255, 153));
        btnRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/retroceder.png"))); // NOI18N
        btnRetroceder.setText("Retroceder");
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(898, 15, -1, -1));

        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/fondo1.png"))); // NOI18N
        getContentPane().add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 100, 60));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/imagen_fondo.png"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -5, 1040, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("Nombre");
    modelo.addColumn("Documento");
    modelo.addColumn("Fecha");
    modelo.addColumn("Hora");
    modelo.addColumn("Motivo");

    try (BufferedReader br = new BufferedReader(new FileReader("baseDeDatos/citas.csv"))) {
        String linea;
        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(",");
            modelo.addRow(datos);
        }
        tablacitas.setModel(modelo);
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al leer las citas: " + e.getMessage());
    }
        
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        int fila = tablacitas.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una cita para editar.");
        return;
    }

    DefaultTableModel modelo = (DefaultTableModel) tablacitas.getModel();

    String nombre = JOptionPane.showInputDialog("Editar nombre:", modelo.getValueAt(fila, 0));
    String documento = JOptionPane.showInputDialog("Editar documento:", modelo.getValueAt(fila, 1));
    String fecha = JOptionPane.showInputDialog("Editar fecha:", modelo.getValueAt(fila, 2));
    String hora = JOptionPane.showInputDialog("Editar hora:", modelo.getValueAt(fila, 3));
    String motivo = JOptionPane.showInputDialog("Editar motivo:", modelo.getValueAt(fila, 4));

    modelo.setValueAt(nombre, fila, 0);
    modelo.setValueAt(documento, fila, 1);
    modelo.setValueAt(fecha, fila, 2);
    modelo.setValueAt(hora, fila, 3);
    modelo.setValueAt(motivo, fila, 4);
    }//GEN-LAST:event_btneditarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        int fila = tablacitas.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una cita para eliminar.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar esta cita?", "Confirmar", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        DefaultTableModel modelo = (DefaultTableModel) tablacitas.getModel();
        modelo.removeRow(fila);

        // Reescribe el archivo CSV
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("baseDeDatos/citas.csv"))) {
            for (int i = 0; i < modelo.getRowCount(); i++) {
                bw.write(modelo.getValueAt(i, 0) + "," +
                         modelo.getValueAt(i, 1) + "," +
                         modelo.getValueAt(i, 2) + "," +
                         modelo.getValueAt(i, 3) + "," +
                         modelo.getValueAt(i, 4));
                bw.newLine();
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar cita: " + e.getMessage());
        }
    }
        
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        // TODO add your handling code here:
        new interfaz_administrador().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRetrocederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new gestionar_citas_admin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneditar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JTable tablacitas;
    // End of variables declaration//GEN-END:variables
}
