package concesionarioapp;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Reverie Pink
 */
public class interfaz_clienteCatagalo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfaz_clienteCatagalo.class.getName());

    /**
     * Creates new form interfaz_clienteCatagalo
     */
 public interfaz_clienteCatagalo() {
    initComponents();
    jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
    cargarCatalogoCliente();
}

private void cargarCatalogoCliente() {
   jPanel2.removeAll(); // Limpia antes de recargar

    // Layout que apila verticalmente los vehículos
    jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));

    int contador = 0;

    try (BufferedReader br = new BufferedReader(new FileReader("baseDeDatos/coches.csv"))) {
        String linea;
        br.readLine(); // Saltar encabezado

        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(",");

            if (datos.length < 8) continue;

            String marca = datos[0];
            String modelo = datos[1];
            String año = datos[2];
            String precio = datos[3];
            String kilometraje = datos[4];
            String descripcion = datos[5];
            String placa = datos[6];
            String rutaImagen = datos[7];

            // Panel individual del vehículo
            JPanel panelVehiculo = new JPanel(new BorderLayout(10, 10));
            panelVehiculo.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY, 1));
            panelVehiculo.setBackground(Color.WHITE);
            panelVehiculo.setMaximumSize(new Dimension(Integer.MAX_VALUE, 160)); // Ajusta la altura
            panelVehiculo.setPreferredSize(new Dimension(550, 160));

            // Imagen
            JLabel lblImagen = new JLabel();
            try {
                ImageIcon icon = new ImageIcon(rutaImagen);
                Image img = icon.getImage().getScaledInstance(150, 100, Image.SCALE_SMOOTH);
                lblImagen.setIcon(new ImageIcon(img));
            } catch (Exception e) {
                lblImagen.setText("Sin imagen");
            }

            // Texto
            JTextArea txtInfoVehiculo = new JTextArea(
                "Marca: " + marca + "\n" +
                "Modelo: " + modelo + "\n" +
                "Año: " + año + "\n" +
                "Precio: " + precio + "\n" +
                "Kilometraje: " + kilometraje + "\n" +
                "Descripción: " + descripcion + "\n" +
                "Placa: " + placa
            );
            txtInfoVehiculo.setEditable(false);
            txtInfoVehiculo.setBackground(Color.WHITE);

            // Armar panel
            panelVehiculo.add(lblImagen, BorderLayout.WEST);
            panelVehiculo.add(txtInfoVehiculo, BorderLayout.CENTER);

            // Agregar al contenedor
            jPanel2.add(panelVehiculo);
            jPanel2.add(Box.createRigidArea(new Dimension(0, 15))); // Espacio entre tarjetas

            contador++;
        }

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar el catálogo: " + e.getMessage());
    }

    if (contador == 0) {
        JLabel lblVacio = new JLabel("No hay vehículos disponibles.");
        lblVacio.setAlignmentX(CENTER_ALIGNMENT);
        jPanel2.add(lblVacio);
    }

    // Este es el truco clave: forzar que el panel crezca más que la vista
    jPanel2.setPreferredSize(new Dimension(jScrollPane1.getWidth() - 30, contador * 180));

    jPanel2.revalidate();
    jPanel2.repaint();

    // Asegurar que el scroll se actualice bien
    jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
}


    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        btnactualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnagendarcita = new javax.swing.JButton();
        btncerrarsesion = new javax.swing.JButton();
        lbllogo = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 600, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 181, 600, 430));

        btnactualizar.setBackground(new java.awt.Color(102, 204, 255));
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/actualizar.png"))); // NOI18N
        btnactualizar.setText("Actualizar catalogo");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 630, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Catálogo de Vehículos - Cliente ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        btnagendarcita.setBackground(new java.awt.Color(255, 255, 204));
        btnagendarcita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/citas.png"))); // NOI18N
        btnagendarcita.setText("Agendar citas");
        getContentPane().add(btnagendarcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 700, 159, -1));

        btncerrarsesion.setBackground(new java.awt.Color(255, 51, 51));
        btncerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/cerrar_sesion.png"))); // NOI18N
        btncerrarsesion.setText("Cerrar sesión");
        btncerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarsesionActionPerformed(evt);
            }
        });
        getContentPane().add(btncerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/fondo1.png"))); // NOI18N
        getContentPane().add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 100, 70));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionarioapp/imagen_fondo.png"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
        cargarCatalogoCliente();
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btncerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarsesionActionPerformed
        // TODO add your handling code here:
          // 1. Ocultar la ventana actual (el catálogo del cliente)
    this.dispose();

    // 2. Crear y mostrar la ventana de inicio de sesión
    inicioApp inicio = new inicioApp();
    inicio.setVisible(true);
    }//GEN-LAST:event_btncerrarsesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interfaz_clienteCatagalo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnagendarcita;
    private javax.swing.JButton btncerrarsesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lbllogo;
    // End of variables declaration//GEN-END:variables

    private static class inicioApp {

        public inicioApp() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
}
